language: node_js
sudo: required
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
script:
  - npm run docs:build
  - cd docs/.vuepress/dist
  - git init
  - git remote add origin "https://${REF}"    #设置要托管到的仓库名
  - git add .                               #添加_book目录下的所有文件
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages" 
  - git branch -M master
  - git push --force --quiet "https://${GH_TOKEN}@${REF}" master:gh-pages  #强制推送到gh-pages分支
  
branches:
  only:
    - master

env:
  global:
    - REF=github.com/hanyanjun/node-start.git # 设置 github 